/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mensajes;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author miguel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        initData();
    }
    
    public void initData(){
            String driver,conexion,usuario,password;
        //driver="com.mysql.jdbc.Driver";// nombre del driver 
        conexion="jdbc:mysql://192.168.2.2:3306/sapao";//jdbc:postgreslq://ubicacion_de_BD:puerto/nombre_BD
        usuario="demonio";
        password="12345";
        try{
 //Class.forName(driver);
        Connection con = (Connection) DriverManager.getConnection(conexion, usuario , password);
        Statement stmt = (Statement) con.createStatement();
 
        ResultSet rs = stmt.executeQuery("SELECT nombre_colonia FROM sapao.colonia;");
        ArrayList<String> col=new ArrayList<>();
        while(rs.next()){
            col.add(rs.getString("nombre_colonia"));
        }
        colonias.setModel(new javax.swing.DefaultComboBoxModel(col.toArray()));
        rs.close();
        
        stmt.close();
        con.close();
 
}
 
catch ( Exception e ){
 System.out.println(e.getMessage());
 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImageReflect1 = new org.edisoncor.gui.panel.PanelImageReflect();
        fondo = new org.edisoncor.gui.panel.PanelRoundTranslucido();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        buttonTask1 = new org.edisoncor.gui.button.ButtonTask();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        colonias = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        panelImageReflect1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gjTW6118.jpeg"))); // NOI18N
        panelImageReflect1.setMaximumSize(new java.awt.Dimension(600, 600));

        labelMetric1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric1.setText("Escribe la publicacion");
        labelMetric1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMetric1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        panelImageReflect1.add(fondo);
        fondo.setBounds(10, 70, 280, 320);

        buttonTask1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TELEGRAM APP ICONO.png"))); // NOI18N
        buttonTask1.setText("Enviar");
        buttonTask1.setToolTipText("");
        buttonTask1.setDescription("presiona para enviar");
        buttonTask1.setFocusable(false);
        buttonTask1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTask1ActionPerformed(evt);
            }
        });
        panelImageReflect1.add(buttonTask1);
        buttonTask1.setBounds(10, 390, 270, 70);
        panelImageReflect1.add(clockFace1);
        clockFace1.setBounds(510, 360, 170, 160);

        labelHeader1.setText("Selecciona la Colonia:");
        panelImageReflect1.add(labelHeader1);
        labelHeader1.setBounds(340, 110, 280, 17);

        panelImageReflect1.add(colonias);
        colonias.setBounds(340, 130, 280, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageReflect1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageReflect1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTask1ActionPerformed
       String msg=texto.getText();
        StringBuffer sb = new StringBuffer();
       Pattern p = Pattern.compile("\\\n");
            Matcher m = p.matcher(msg);
       while(m.find()){
           m.appendReplacement(sb," ");
       }
        m.appendTail(sb);
        
        
           String driver,conexion,usuario,password;
        //driver="com.mysql.jdbc.Driver";// nombre del driver 
        conexion="jdbc:mysql://localhost:3306/sapao";//jdbc:postgreslq://ubicacion_de_BD:puerto/nombre_BD
        usuario="demonio";
        password="12345";
        try{
 //Class.forName(driver);
        Connection con = (Connection) DriverManager.getConnection(conexion, usuario , password);
        Statement stmt = (Statement) con.createStatement();
 
        ResultSet rs = stmt.executeQuery("SELECT id_telegram FROM sapao.colonia natural join sapao.usuario where nombre_colonia='"+colonias.getItemAt(colonias.getSelectedIndex())+"';");
        while(rs.next()){
            System.out.print("eniviar"+rs.getString("id_telegram"));
            EnviarMensaje mensaje;
            mensaje = new EnviarMensaje(rs.getString("id_telegram"),sb.toString());
            mensaje.start();
           
                
            }
        
         rs.close();
        
        stmt.close();
        con.close();
        
        }
 
        catch ( Exception e ){
            System.out.println(e.getMessage());
                }
    }//GEN-LAST:event_buttonTask1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask buttonTask1;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JComboBox colonias;
    private org.edisoncor.gui.panel.PanelRoundTranslucido fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.panel.PanelImageReflect panelImageReflect1;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
